input_dir: ~/gnnfiles/data/ntuple_PU200_numEvent1000/ntuple_PU200_event0.h5

num_states: 4
num_actions: 2 
upper_bound_r: 26
lower_bound_r: 0
upper_bound_z: 266
lower_bound_z: -266
upper_bound: [26, 266]
lower_bound: [0, -266]