file_prefix: '/home/lhv14/exatrkx/Tracking-ML-Exa.TrkX/alldata/train_1_processed1000/processed_event00000'
md_file: 'new_md_hitbased.csv'
num_states: 9
num_actions: 4
upper_bound_r: 100
lower_bound_r: 0
upper_bound_z: 300
lower_bound_z: -300
upper_bound: [300, 26]
lower_bound: [-300, 0]
num_close_hits: 10
#num_comp_hits: 5